export const REQUEST_POST_CREATE='REQUEST_POST_CREATE'
export const CREATE_POST = 'CREATE_POST'


export const FETCH_POST = 'FETCH_POSTS'
export const REQUEST_POSTS ='REQUEST_POSTS'

export const SIGN_IN = 'SIGN_IN'
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN'
export const LOG_OUT = 'LOG_OUT'

export const FETCH_AUTH_USER = 'FETCH_AUTH_USER';
export const REQUEST_AUTH_USER = 'REQUEST_AUTH_USER';

export const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';

export const REQUEST_CREATE_COMMENT = 'REQUEST_CREATE_COMMENT';
export const CREATE_COMMENT = 'CREATE_COMMENT'

export const REQUEST_PUT_POST = 'REQUEST_PUT_POST';
export const PUT_POST = 'PUT_POST'

export const REQUEST_DELETE_POST = 'REQUEST_DELETE_POST';
export const DELETE_POST = 'DELETE_POST';

export const REQUEST_USERS_ME = 'REQUEST_USERS_ME';
export const USERS_ME = 'USERS_ME'

export const REQUEST_GET_POST = 'REQUEST_GET_POST'
export const GET_POST = 'GET_POST'